# Change these first
owner: ForesightMiningSoftwareCorporation
repo: upptime

sites:
  - name: Production server
    url: $PREDICT_PROD_URL/healthz

status-website:
  cname: status.foresightmining.com
  name: ForesightMiningSoftwareCorporation
  apiBaseUrl: https://ee20a4bc53c6.ngrok.app
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  publish: true
