# Change these first
owner: ForesightMiningSoftwareCorporation
repo: upptime
sites:
  - name: Production server
    url: $PREDICT_PROD_URL/healthz
  - name: Whirlpool updates
    url: $PREDICT_PROD_URL/fse/update?software=whirlpool&channel=nightly&platform=windows
  - name: Development server
    url: $PREDICT_DEV_URL/healthz

status-website:
  cname: status.foresightmining.com
  name: ForesightMiningSoftwareCorporation
  apiBaseUrl: https://gh.dc1.foresightmining.com/status-board
  userContentBaseUrl: https://gh.dc1.foresightmining.com/status-board
  theme: dark
  runner: "[self-hosted, standard]"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  publish: true
