# Change these first
owner: ForesightMiningSoftwareCorporation
repo: upptime

sites:
  - name: Production server
    url: $PREDICT_PROD_URL/healthz

status-website:
  cname: status.foresightmining.com
  name: ForesightMiningSoftwareCorporation
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
